<?php

/**
 * Valeurs par défaut de la page d'accueil (fusionnées avec la base `home_sections`).
 *
 * @return array<string, mixed>
 */
return [
    'meta' => [
        'title' => 'Normes & Rénovation — Rénovation énergétique en Bourgogne',
        'description' => 'Normes & Rénovation accompagne vos projets de rénovation énergétique, thermique et électrique en Bourgogne. Devis gratuit, entreprise certifiée RGE.',
        'description_social' => 'Devis gratuit, entreprise certifiée RGE en Bourgogne. Rénovation énergétique, thermique, électrique et toiture — accompagnement complet.',
        'og_image' => 'logo.png',
        'og_image_alt' => 'Normes & Rénovation — logo',
        'theme_color' => '#2F4251',
        'favicon' => '/iconne.png',
        'site_name' => 'Normes & Rénovation',
    ],

    'styles' => [
        'footer_bg' => '/slide/toiture.png',
        'aides_bg' => 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=2000&q=80',
    ],

    'header' => [
        'logo' => '/logo.png',
        'logo_alt' => 'Normes & Rénovation',
        'menu_items' => [
            ['label' => 'Accueil', 'route' => 'home', 'anchor' => '', 'custom_url' => '', 'style' => ''],
            ['label' => 'Toiture', 'route' => 'home', 'anchor' => 'services', 'custom_url' => '', 'style' => ''],
            ['label' => 'Façade', 'route' => 'home', 'anchor' => 'services', 'custom_url' => '', 'style' => ''],
            ['label' => 'Isolation', 'route' => 'home', 'anchor' => 'services', 'custom_url' => '', 'style' => ''],
            ['label' => 'Énergie', 'route' => 'home', 'anchor' => 'services', 'custom_url' => '', 'style' => ''],
            ['label' => 'Le réseau', 'route' => 'home', 'anchor' => 'a-propos', 'custom_url' => '', 'style' => ''],
            ['label' => 'Réalisations', 'route' => 'realisations.page', 'anchor' => '', 'custom_url' => '', 'style' => ''],
            ['label' => 'Franchise', 'route' => 'franchise.page', 'anchor' => '', 'custom_url' => '', 'style' => ''],
            ['label' => 'Conseils', 'route' => 'home', 'anchor' => 'conseils', 'custom_url' => '', 'style' => ''],
            ['label' => 'Devis', 'route' => 'contact.page', 'anchor' => 'devis', 'custom_url' => '', 'style' => 'cta'],
        ],
        'social' => [
            ['network' => 'facebook', 'url' => '#', 'label' => 'Facebook'],
            ['network' => 'linkedin', 'url' => '#', 'label' => 'LinkedIn'],
            ['network' => 'instagram', 'url' => '#', 'label' => 'Instagram'],
        ],
    ],

    'hero' => [
        'slides' => [
            [
                'identity' => true,
                'image' => 'slide/toiture.png',
                'title' => "L'expert rénovation énergétique et entretien de la maison en Bourgogne",
                'subtitle' => 'Normes & Rénovation accompagne vos projets de rénovation, thermique, toiture et énergie solaire. Certifié RGE, devis gratuit.',
                'primary_text' => 'Devis gratuit',
                'primary_href' => '#devis',
                'secondary_text' => 'Nos services',
                'secondary_href' => '#services',
            ],
            [
                'image' => 'slide/solaire.png',
                'type' => 'solar-kit',
                'eyebrow' => 'Spécialiste du kit solaire en Bourgogne',
                'title' => 'Votre kit solaire, prêt à simuler chez vous',
                'subtitle' => 'Choisissez votre puissance, entrez votre adresse et visualisez rapidement votre projet solaire.',
                'primary_text' => 'Lancer ma simulation',
                'primary_href' => '/simulateur-solaire',
                'secondary_text' => 'Voir le solaire',
                'secondary_href' => '#services',
                'kit_options' => [
                    ['kwc' => '3', 'label' => '3 kWc', 'description' => 'Maison 2-3 personnes', 'badge' => 'Le plus choisi'],
                    ['kwc' => '4', 'label' => '4 kWc', 'description' => 'Maison 3-4 personnes'],
                    ['kwc' => '6', 'label' => '6 kWc', 'description' => 'Maison familiale'],
                    ['kwc' => '9', 'label' => '9 kWc', 'description' => 'Grande maison'],
                ],
            ],
            [
                'image' => 'slide/toiture.png',
                'title' => 'Travaux de toiture durables et performants',
                'subtitle' => 'Protection, étanchéité et rénovation complète de votre toiture pour valoriser votre maison.',
                'primary_text' => 'Devis toiture',
                'primary_href' => '#devis',
                'secondary_text' => 'Nous contacter',
                'secondary_href' => '#devis',
            ],
        ],
    ],

    'simulateur' => [
        'label' => 'Entrez votre adresse (simulateur)',
        'placeholder' => 'Ex: 6 rue Pierre de Coubertin, Chalon-sur-Saone',
        'button' => 'Lancer le simulateur',
    ],

    'floating' => [
        'google_url' => 'https://share.google/14Nu70a8PfwWT4P4p',
        'logo' => '/logo.png',
        'title' => '5.0/5 — Avis Google',
        'subtitle' => '★★★★★',
        'subtitle_suffix' => '+100 avis',
        'link_text' => 'Voir les avis →',
        'phone' => '+33385419886',
        'phone_display' => '03 85 41 98 86',
    ],

    'sidebar_avis' => [
        'google_url' => 'https://share.google/14Nu70a8PfwWT4P4p',
        'icon' => '/iconne.png',
        'icon_alt' => 'Icone Normes & Renovation',
        'label' => 'Avis Google',
        'score' => '5.0/5',
        'stars' => '★★★★★',
        'text' => '+100 avis',
    ],

    'services' => [
        'title_accent' => 'Nos services',
        'title_rest' => ' de rénovation',
        'intro' => 'Découvrez nos services principaux, pensés pour protéger, améliorer et valoriser votre habitat.',
        'items' => [
            [
                'num' => 1,
                'category' => 'toiture',
                'image' => 'services/nettoyage-demoussage-toiture.jpeg',
                'title' => 'Traitement et démoussage de toiture',
                'description' => 'Nettoyage complet, élimination des mousses et application de traitement hydrofuge pour protéger durablement votre toiture.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 2,
                'category' => 'toiture',
                'image' => 'slide/toiture.png',
                'title' => 'Remplacement de couverture et zinguerie',
                'description' => 'Réfection complète de toiture, pose de tuiles et éléments de zinguerie pour garantir l’étanchéité et la longévité.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 3,
                'category' => 'isolation',
                'image' => 'services/isolation-thermique.jpeg',
                'title' => 'Isolation thermique',
                'description' => 'Isolation des combles, rampants et planchers pour améliorer le confort et réduire les pertes de chaleur.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 4,
                'category' => 'air',
                'image' => 'services/ventilation-vmc-vmi.jpg',
                'title' => 'Ventilation (VMC / VMI)',
                'description' => 'Installation de systèmes de ventilation pour assainir l’air intérieur et lutter contre l’humidité.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 5,
                'category' => 'energie',
                'image' => 'services/installation-photovoltaique.jpg',
                'title' => 'Installation photovoltaïque',
                'description' => 'Production d’électricité solaire pour réduire vos factures et améliorer votre autonomie énergétique.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 6,
                'category' => 'air',
                'image' => 'services/climatisation-ete.jpg',
                'title' => 'Climatisation',
                'description' => 'Installation de systèmes de climatisation performants pour un intérieur confortable en toute saison.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 7,
                'category' => 'menuiserie',
                'image' => 'services/menuiserie2.jpg',
                'title' => 'Menuiserie',
                'description' => 'Installation et remplacement de fenêtres, portes et menuiseries pour améliorer l’isolation et la sécurité.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 8,
                'category' => 'facade',
                'image' => 'services/renovation-facade.jpeg',
                'title' => 'Rénovation de façade',
                'description' => 'Nettoyage, peinture et traitement de façade pour protéger et valoriser votre habitation.',
                'cta' => 'En savoir plus',
            ],
            [
                'num' => 9,
                'category' => 'autres',
                'image' => 'services/traitement-charpente.webp',
                'title' => 'Autres services',
                'description' => 'Adoucisseur d’eau, traitement de charpente, entretien des gouttières et solutions complémentaires pour une maison saine.',
                'cta' => 'En savoir plus',
            ],
        ],
    ],

    'realisations' => [
        'title_accent' => 'Avant',
        'title_rest' => ' / Après',
        'intro' => 'Comparez plusieurs chantiers et voyez l\'impact concret de nos rénovations.',
        'buttons' => [
            ['case' => 1, 'label' => 'Toiture'],
            ['case' => 2, 'label' => 'Façade'],
        ],
        'cases' => [
            ['before' => 'avantapres/toitureavant.png', 'after' => 'avantapres/toitureapres.png'],
            ['before' => 'avantapres/facadeavant.png', 'after' => 'avantapres/facadeapres.png'],
        ],
        'cta_title' => 'Vous avez un projet de rénovation ?',
        'cta_text' => 'Décrivez votre besoin : nous vous recontactons rapidement avec un accompagnement personnalisé, vos options d\'aides et une première base pour votre devis.',
        'cta_button' => 'Ouvrir le simulateur de devis',
        'cta_href' => '#devis',
        'promo_kicker' => 'Réalisations',
        'promo_title' => 'Voir toutes nos réalisations',
        'promo_text' => 'Découvrez nos chantiers avant/après et les transformations déjà réalisées pour nos clients.',
        'promo_button' => 'Explorer les réalisations',
        'promo_href' => '',
        'promo_bg' => 'avantapres/toitureapres.png',
    ],

    'about' => [
        'title' => 'À propos de Normes & Rénovation',
        'body' => 'Normes & Rénovation accompagne les particuliers et professionnels dans leurs projets de rénovation énergétique, thermique et électrique. Notre équipe combine expertise technique, suivi de chantier et conseils sur mesure pour des résultats fiables et durables. Nous sommes certifiés RGE, engagés dans le respect de l\'environnement et nous privilégions des matériaux de qualité pour des rénovations performantes et responsables.',
        'commitments_heading' => 'Nos engagements',
        'commitments' => [
            'Garantie sur les travaux réalisés',
            'Nous nous occupons de tout pour vous simplifier la vie',
            'Techniciens qualifiés et formés en continu',
            'Entreprise certifiée et orientée qualité',
            'Accompagnement complet de l\'étude à la livraison',
            'Solutions performantes pour valoriser votre bien',
        ],
        'cert_images' => [
            ['src' => '/nous/rge.png', 'alt' => 'Logo RGE Qualibat'],
            ['src' => '/nous/rge ventilation_.png', 'alt' => 'Logo RGE Ventilation'],
            ['src' => '/nous/ECO.png', 'alt' => 'Logo Eco Responsable'],
        ],
        'team_image' => '/nous/equipe.jpeg',
        'team_alt' => 'Équipe Normes & Rénovation',
    ],

    'agences' => [
        'title_accent' => 'Nos',
        'title_rest' => ' agences',
        'intro' => 'Retrouvez nos 2 agences principales et les départements mis en avant sur la carte.',
        'agencies' => [
            [
                'badge' => 'DÉPARTEMENT 71',
                'name' => 'Agence Chalon-sur-Saône',
                'address' => '6 rue Pierre de Coubertin, 71100 Chalon-sur-Saône',
                'phone' => '03 85 41 98 86',
                'phone_href' => '+33385419886',
            ],
            [
                'badge' => 'DÉPARTEMENT 22 — BRETAGNE',
                'name' => 'Agence Bretagne',
                'address' => 'ZA de Mikez — 22540 Pédernec',
                'phone' => '02 96 40 07 55',
                'phone_href' => '+33296400755',
            ],
        ],
        'franchise' => [
            'image' => 'https://images.unsplash.com/photo-1556155092-490a1ba16284?auto=format&fit=crop&w=1200&q=80',
            'kicker' => 'RÉSEAU NORMES',
            'title' => 'Devenir franchisé',
            'text' => 'Rejoignez notre réseau et développez votre agence avec un accompagnement complet — contactez-nous pour en discuter.',
            'button' => 'Demander une présentation / devenir franchisé',
            'href' => '#devis',
        ],
        'map_box' => [
            'title_accent' => 'Carte',
            'title_rest' => ' des implantations',
            'legend_1' => 'Région Bretagne',
            'legend_2' => 'Départements 71 & 21',
        ],
    ],

    'pourquoi' => [
        'title_accent' => 'Pourquoi',
        'title_rest' => ' nous ?',
        'intro' => 'Des engagements concrets, visibles en un coup d\'œil.',
        'cards' => [
            ['emoji' => '🛠️', 'title' => 'Expertise technique', 'text' => 'Des équipes qualifiées et des conseils adaptés à votre maison.', 'ring' => 'brand-blue/15'],
            ['emoji' => '✅', 'title' => 'Entreprise certifiée RGE', 'text' => 'Un accompagnement conforme aux normes et aux aides en vigueur.', 'ring' => 'brand-yellow/25'],
            ['emoji' => '🌿', 'title' => 'Solutions durables', 'text' => 'Des produits et matériaux sélectionnés pour leur performance, leur longévité et un impact environnemental maîtrisé.', 'ring' => 'emerald-500/20'],
            ['emoji' => '🤝', 'title' => 'Accompagnement complet', 'text' => 'Un interlocuteur unique du devis jusqu\'à la fin de chantier.', 'ring' => 'sky-400/25', 'wide' => true],
        ],
    ],

    'processus' => [
        'title_accent' => 'Processus',
        'title_rest' => ' de prise en charge',
        'intro' => 'Quatre étapes claires, de l\'estimation de vos aides au suivi de chantier.',
        'steps' => [
            [
                'num' => '1',
                'num_style' => 'brand-blue',
                'title' => 'Calcul de primes et devis précis',
                'text' => 'Nous nous occupons du calcul de vos primes, des CEE (certificats d\'économies d\'énergie) et des options de financement. Travaux couverts jusqu\'à 90 % sans avance de frais dans les cas éligibles.',
            ],
            [
                'num' => '2',
                'num_style' => 'brand-dark-yellow',
                'title' => 'Solutions de financement',
                'text' => 'Des solutions adaptées avec nos partenaires pour financer le coût des travaux de rénovation.',
            ],
            [
                'num' => '3',
                'num_style' => 'brand-dark-white',
                'title' => 'Analyse personnalisée',
                'text' => 'Un technicien qualifié se déplace gratuitement pour un diagnostic approfondi de vos besoins.',
            ],
            [
                'num' => '4',
                'num_style' => 'gradient',
                'title' => 'Suivi et assistance continus',
                'text' => 'De la première consultation à la fin des travaux : suivi régulier et assistance pour une exécution sereine.',
                'span' => true,
            ],
        ],
    ],

    'aides_renov' => [
        'logo' => '/nous/ma prime.png',
        'logo_alt' => 'Programme MaPrimeRénov\' — Mieux chez moi, mieux pour la planète',
        'logo_caption' => 'MaPrimeRénov\' · dispositif national',
        'logo_sub' => 'Accompagnement dossier & cumul avec les CEE',
        'kicker' => 'Aides à la rénovation',
        'title' => 'On vous accompagne pour vos aides MaPrimeRénov\' et CEE',
        'body' => 'Notre équipe vous aide à comprendre vos droits, à monter les dossiers MaPrimeRénov\' et à valoriser les certificats d\'économies d\'énergie (CEE) éligibles sur votre projet. Nous optimisons le cumul des dispositifs pour limiter votre reste à charge et sécuriser vos travaux.',
        'button' => 'Demander un accompagnement',
        'footnote' => 'RGE · Devis gratuit · Réponse rapide',
    ],

    'stats' => [
        'items' => [
            ['number' => '5000', 'prefix' => '+', 'suffix' => '', 'label' => 'Chantiers réalisés', 'icon' => 'fa-solid fa-building', 'animate' => true],
            ['number' => '98', 'prefix' => '', 'suffix' => '%', 'label' => 'Satisfaction client', 'icon' => 'fa-solid fa-star', 'animate' => true],
            ['number' => '48', 'prefix' => '', 'suffix' => 'h', 'label' => 'Prise en charge rapide', 'icon' => 'fa-solid fa-clock', 'animate' => false],
            ['number' => '100', 'prefix' => '', 'suffix' => '%', 'label' => 'Devis gratuit', 'icon' => 'fa-solid fa-file-lines', 'animate' => false],
        ],
    ],

    'avis' => [
        'title_accent' => 'Ce que nos clients pensent de nous',
        'title_rest' => ': avis client',
        'intro' => 'Ils nous font confiance pour leurs travaux de rénovation. Découvrez tous les retours sur notre fiche Google.',
        'google_url' => 'https://share.google/14Nu70a8PfwWT4P4p',
        'google_button' => 'Voir la fiche',
        'testimonials' => [
            [
                'platform' => 'google',
                'review_count' => '+100 avis',
                'text' => 'Équipe sérieuse, chantier propre et très bon résultat.',
                'author' => 'Claire M.',
                'deco_class' => 'bg-brand-blue/5',
            ],
            [
                'platform' => 'google',
                'review_count' => '+100 avis',
                'text' => 'Accompagnement pro du début à la fin et très bons conseils.',
                'author' => 'Julien R.',
                'deco_class' => 'bg-brand-yellow/10',
            ],
            [
                'platform' => 'travaux.com',
                'review_count' => '+60 avis',
                'text' => 'Intervention soignée, délais respectés et communication claire à chaque étape.',
                'author' => 'Marion B.',
                'deco_class' => 'bg-brand-blue/5',
            ],
            [
                'platform' => 'travaux.com',
                'review_count' => '+60 avis',
                'text' => 'Devis précis, équipe ponctuelle et conseils adaptés à notre maison.',
                'author' => 'Nicolas D.',
                'deco_class' => 'bg-brand-yellow/10',
            ],
            [
                'platform' => 'trustpilot',
                'review_count' => '+45 avis',
                'text' => 'Travail de qualité, finitions propres et équipe très à l\'écoute.',
                'author' => 'Sophie L.',
                'deco_class' => 'bg-emerald-500/10',
            ],
            [
                'platform' => 'google',
                'review_count' => '+100 avis',
                'text' => 'Très bon suivi du devis jusqu\'à la fin de chantier. Résultat impeccable.',
                'author' => 'Thomas K.',
                'deco_class' => 'bg-brand-blue/5',
            ],
        ],
    ],

    'contact_page' => [
        'hero_bg' => '/slide/toiture.png',
        'featured_image' => '/slide/toiture.png',
        'meta_title' => 'Contact | Normes & Rénovation',
        'meta_description' => 'Contactez-nous pour un devis gratuit, une question sur votre chantier ou nos agences. Réponse sous 48 h en général.',
        'meta_keywords' => '',
        'og_image' => '/slide/toiture.png',
        'hero_kicker' => 'Contact',
        'hero_title_line1' => 'Vous avez',
        'hero_title_line2' => 'un projet de rénovation ?',
        'hero_subtitle' => 'Estimation personnalisée & rappel d\'un conseiller',
        'hero_intro' => 'Visualisez les grandes lignes de votre projet (toiture, surfaces, état du bien) — un interlocuteur vous rappelle pour affiner chiffrage et aides.',
        'hero_cta_form' => 'Formulaire de contact',
        'hero_cta_phone' => '03 85 41 98 86',

        'labels' => [
            'siege' => 'Siège social',
            'phone' => 'Téléphone',
            'email' => 'E-mail',
            'hours' => 'Horaires',
            'social' => 'Réseaux sociaux',
            'map' => 'Carte',
        ],

        'social_bg' => '/slide/toiture.png',
        'social_title' => 'Suivez nos actualités',
        'social_intro' => 'Retrouvez-nous sur les réseaux pour nos chantiers, conseils et nouveautés.',

        'map_title' => 'Nos implantations',
        'map_intro' => 'Repérez nos agences en un coup d’œil (Bretagne et Bourgogne).',

        'cta_card' => [
            'kicker' => 'Un projet de rénovation ?',
            'title' => 'Démarrez dès maintenant',
            'text' => 'Lancez le simulateur pour une première estimation, ou envoyez votre demande pour être contacté rapidement.',
            'simulateur_text' => 'Ouvrir le simulateur de devis',
            'contact_text' => 'Accéder au formulaire de contact',
        ],
    ],

    'about_page' => [
        'hero_bg' => '/slide/toiture.png',
        'meta_title' => 'À propos | Normes & Rénovation',
        'meta_description' => 'Normes et Rénovation : rénovation de maison, traitement de l’humidité, performance énergétique et solutions durables. Expertise technique, avis clients et coordonnées.',
        'meta_keywords' => '',
        'og_image' => '/slide/toiture.png',
        'hero_kicker' => 'Notre entreprise',
        'hero_title' => 'CONSTRUISEZ AVEC NOUS, BÂTISSEZ L’AVENIR',
        'hero_intro' => 'Normes et Rénovation est une entreprise spécialisée dans la Rénovation de maison, offrant des solutions complètes pour traiter l’humidité, améliorer l’efficacité énergétique et assurer la durabilité de votre habitation.',
        'company_story_kicker' => 'Qui sommes-nous',
        'company_story_heading' => 'Normes et Rénovation, votre partenaire rénovation',
        'company_story_body' => 'Normes et Rénovation est une entreprise de rénovation et d’amélioration de l’habitat, ancrée sur le terrain et tournée vers le long terme. Nous intervenons sur les projets de rénovation de la maison : humidité et pathologies liées à l’eau, isolation et performance thermique, sécurité et mise aux normes des installations, tout en privilégiant des solutions durables et intelligibles pour les propriétaires.

Notre nom reflète notre exigence : respecter les règles de l’art et les normes en vigueur, pour des chantiers documentés et des finitions sérieuses. Nous préférons le conseil transparent aux promesses rapides : diagnostic clair, périmètre défini, et accompagnement jusqu’à la réception.

Nous travaillons avec des équipes et des corps de métier complémentaires pour offrir une réponse cohérente sur les parties couverture, façade, second œuvre et confort intérieur, selon les besoins de votre bien. Notre objectif est simple : vous livrer un habitat plus sain, plus confortable et mieux protégé dans le temps.',
        'company_story_image' => '/nous/equipe.jpeg',
        'company_story_image_alt' => 'L’équipe Normes et Rénovation au travail',
        'reels_section_kicker' => 'Nos réalisations',
        'reels_section_title' => 'Découvrez notre savoir-faire en vidéo',
        'reels' => [
            ['video' => '', 'image' => '', 'caption' => ''],
            ['video' => '', 'image' => '', 'caption' => ''],
            ['video' => '', 'image' => '', 'caption' => ''],
            ['video' => '', 'image' => '', 'caption' => ''],
        ],
        'contact_strip_title' => 'NOUS CONTACTEZ',
        'contact_strip_compact_title' => 'NOUS CONTACTEZ',
        'pillars_kicker' => 'Expertise et Durabilité',
        'pillars_title' => 'Un partenaire fiable|à chaque étape',
        'pillars' => [
            ['title' => 'Expertise Technique', 'text' => 'Diagnostics et interventions adaptés à chaque chantier.'],
            ['title' => 'Solutions Personnalisées', 'text' => 'Des réponses sur mesure pour votre logement et votre projet.'],
            ['title' => 'Innovation et Technologies Modernes', 'text' => 'Matériaux et équipements performants pour durer.'],
            ['title' => 'Service Client Exceptionnel', 'text' => 'Écoute, transparence et suivi tout au long du projet.'],
        ],
        'expertise_title' => 'Expertise complète|en rénovation',
        'expertise_text' => 'Normes et Rénovation se spécialise dans une gamme étendue de services de rénovation, incluant la gestion de l’humidité, l’amélioration de l’efficacité énergétique et la sécurité des installations électriques. Nous offrons des solutions sur mesure pour répondre aux besoins spécifiques de chaque projet.',
        'expertise_image' => '/slide/toiture.png',
        'eco_title' => 'Solutions écologiques|et durables',
        'eco_text' => 'Nous privilégions des solutions respectueuses de l’environnement, telles que les traitements hydrofuges pour façades et les systèmes de ventilation innovants. Nous nous engageons à utiliser des technologies durables qui améliorent le confort tout en réduisant l’empreinte écologique.',
        'eco_image' => '/nous/equipe.jpeg',
        'avis_section_kicker' => 'VOS AVIS',
        'avis_section_title' => 'Ce que disent|nos clients',
        'google_reviews_label' => '98 avis Google',
        'google_url' => 'https://share.google/14Nu70a8PfwWT4P4p',
        'testimonials' => require __DIR__.'/about_testimonials_defaults.php',
        'satisfaction_title' => 'Votre satisfaction|est notre priorité',
        'satisfaction_image' => '/nous/equipe.jpeg',
        'satisfaction_image_alt' => 'Satisfaction client et accompagnement Normes et Rénovation',
        'mediation_text' => 'Conformément à la réglementation, notre établissement a désigné le Centre de la Médiation de la Consommation de Conciliateurs de Justice (CM2C) comme médiateur de la consommation. En cas de réclamation non résolue, vous pouvez le contacter directement à l’adresse https://www.cm2c.net.',
        'tagline_bottom' => 'Spécialiste en solution de rénovation électrique, thermique et hygrométrique pour la maison.',
        'legal' => [
            'show' => true,
            'title' => 'Mentions légales',
            'siege_title' => 'Siège social',
            'contact_title' => 'Contact',
            'representative_title' => 'Représentant légal',
            'representative_text' => 'Conformément aux statuts.',
            'rcs_label' => 'Inscription au registre du commerce et des sociétés',
            'rcs_number' => '900 571 696 00013',
            'siren_label' => 'Numéro SIREN',
            'siren' => '900 571 696',
            'siret_label' => 'Numéro SIRET (siège)',
            'siret' => '900 571 696 00013',
            'tva_label' => 'Numéro d’identification TVA',
            'tva' => 'FR96 900 571 696',
        ],
    ],

    'realisations_page' => [
        'meta_title' => 'Réalisations | Normes & Rénovation',
        'meta_description' => 'Photos et descriptions de chantiers menés par Normes & Rénovation : toiture, façade, isolation, rénovation énergétique et travaux durables.',
        'meta_keywords' => '',
        'og_image' => '/slide/toiture.png',
        'hero_bg' => '/slide/toiture.png',
        'hero_kicker' => 'Chantiers',
        'hero_h1_primary' => 'Nos réalisations',
        'hero_h1_accent' => 'en images',
        'hero_intro' => 'Retrouvez ici une sélection de projets : contexte, travaux réalisés et résultat. Chaque chantier est unique — contactez-nous pour étudier le vôtre.',
    ],

    'devis' => [
        'title_line1' => 'Vous avez',
        'title_line2' => 'un projet de rénovation ?',
        'subtitle' => 'Estimation personnalisée & rappel d\'un conseiller',
        'intro' => 'Visualisez les grandes lignes de votre projet (toiture, surfaces, état du bien) — un interlocuteur vous rappelle pour affiner chiffrage et aides.',
        'response_note' => 'Réponse sous 48h en général — sans engagement.',
        'team_image' => '/nous/camion-chantier.png',
        'team_caption' => 'Nous sommes là pour vous accompagner',
        'team_caption_detail' => 'Une équipe de professionnels certifiés RGE, à votre écoute pour chaque étape de votre projet de rénovation.',
        'mobile_form_cta' => 'Remplir le formulaire',
        'contact_heading' => 'Contact agences',
        'agencies_contact' => [
            [
                'name' => 'Agence Chalon-sur-Saône',
                'lines' => ['6 rue Pierre de Coubertin', '71100 Chalon-sur-Saône'],
                'phone' => '03 85 41 98 86',
                'phone_href' => '+33385419886',
            ],
            [
                'name' => 'Agence Bretagne',
                'lines' => ['ZA de Mikez', '22540 Pédernec'],
                'phone' => '02 96 40 07 55',
                'phone_href' => '+33296400755',
            ],
        ],
        'email' => 'bourgogne-agence@normesrenovation.fr',
        'hours' => 'Horaires : du lundi au vendredi, sur rendez-vous — réponse sous 48h en général.',
        'sim_block' => [
            'kicker' => 'Simulateur de devis',
            'title' => 'Estimez les grandes lignes avec votre adresse',
            'text' => 'Accédez au bandeau simulateur : saisissez votre adresse pour lancer une première analyse ; un conseiller peut ensuite affiner avec vous.',
            'primary' => 'Lancer le simulateur',
            'primary_href' => '#simulateur-devis',
            'secondary' => 'Passer au formulaire',
            'secondary_href' => '#formulaire-contact',
        ],
        'form' => [
            'title' => 'Formulaire de contact',
            'intro' => 'Indiquez vos coordonnées et votre projet pour être rappelé(e) et recevoir une base de devis.',
            'note' => 'Ces informations nous permettent de préparer un devis pertinent.',
            'submit' => 'Envoyer ma demande — devis gratuit',
            'footer_note' => 'Sans engagement. Un conseiller vous rappelle pour affiner votre projet.',
        ],
    ],

    'blog' => [
        'title_accent' => 'Astuces',
        'title_rest' => ' & blog',
        'intro' => 'Conseils pratiques pour préparer vos travaux, mieux comprendre les aides et entretenir votre logement durablement.',
        // Rempli dynamiquement par HomePageService (articles publiés) — pas de cartes fictives.
        'posts' => [],
    ],

    'partners' => [
        'heading' => 'Partenaires & certification',
        'logos' => [
            // Logos "partenaires" (dossier public/partenaire)
            '/partenaire/Calque 2.png',
            '/partenaire/Calque 3.png',
            '/partenaire/Calque 4.png',
            '/partenaire/Calque 5.png',
            '/partenaire/Calque 6.png',
            '/partenaire/Calque 7.png',
            '/partenaire/Calque 8.png',
            '/partenaire/Calque 9.png',
            // Logos de certification RGE (dossier public/nous)
            '/nous/rge.png',
            '/nous/rge ventilation_.png',
            '/nous/ECO.png',
        ],
    ],

    'footer' => [
        'logo' => '/logofooter.png',
        'logo_alt' => 'Normes & Rénovation',
        'siege_title' => 'Siège social',
        'company' => 'Normes et Rénovation',
        'address_lines' => ['6 rue Pierre de Coubertin', '71100 Chalon-sur-Saône'],
        'legal' => 'Représentant légal · Conformément aux statuts · RCS Chalon-sur-Saône — 900 571 696 00013 · SIREN 900 571 696 · SIRET (siège) 900 571 696 00013 · TVA FR96 900 571 696',
        'phone' => '03 85 41 98 86',
        'phone_href' => '+33385419886',
        'email' => 'bourgogne-agence@normesrenovation.fr',
        'quick_links' => [
            ['label' => 'Nos services', 'route' => 'home', 'anchor' => 'services', 'custom_url' => ''],
            ['label' => 'Réalisations', 'route' => 'home', 'anchor' => 'realisations', 'custom_url' => ''],
            ['label' => 'Franchise', 'route' => 'franchise.page', 'anchor' => '', 'custom_url' => ''],
            ['label' => 'Agences & carte', 'route' => 'home', 'anchor' => 'agences', 'custom_url' => ''],
            ['label' => 'Conseils', 'route' => 'home', 'anchor' => 'conseils', 'custom_url' => ''],
            ['label' => 'Contact / devis', 'route' => 'contact.page', 'anchor' => 'devis', 'custom_url' => ''],
        ],
        'networks_note' => 'Lundi au vendredi de 8h30 à 17h. En urgence, appelez l\'agence la plus proche.',
        'copyright_name' => 'Normes et Rénovation',
        'bottom_line' => 'Entreprise RGE — Rénovation énergétique —',
        'bottom_link' => 'Demander un devis',
        'bottom_href' => '#devis',
        'social' => [
            ['network' => 'facebook', 'url' => '#', 'label' => 'Facebook Normes & Rénovation'],
            ['network' => 'linkedin', 'url' => '#', 'label' => 'LinkedIn Normes & Rénovation'],
            ['network' => 'instagram', 'url' => '#', 'label' => 'Instagram Normes & Rénovation'],
        ],
    ],

    'map' => [
        'locations' => [
            ['name' => 'Agence 71 - Chalon-sur-Saône', 'coords' => [46.781, 4.853], 'tag' => '71'],
            ['name' => 'Agence Bretagne - Pédernec', 'coords' => [48.595, -3.286], 'tag' => '22'],
        ],
    ],

    'franchise_page' => [
        'meta_title' => 'Franchise | Devenez franchisé | Normes & Rénovation',
        'meta_description' => 'Devenez franchisé Normes Rénovation : marque reconnue, formation, accompagnement et réseau en Bourgogne et Bretagne. Déposez votre candidature en ligne.',
        'meta_keywords' => 'franchise, franchisé, Normes Rénovation, agence, rénovation, Bourgogne, Bretagne',
        'og_image' => '',

        'brochure_pdf' => '',
        'brochure_label' => 'Télécharger la brochure franchise',

        'hero_bg' => '',
        'hero_kicker' => 'Franchise 100 % rentable',
        'hero_h1_line1' => 'Devenez franchisé',
        'hero_h1_accent' => 'Normes Rénovation',
        'hero_intro' => 'Lancez votre entreprise avec une marque structurée, un marché porteur et un accompagnement de bout en bout — de la formation à la croissance de votre agence.',
        'hero_cta_primary' => 'Commencer mon dossier',
        'hero_cta_secondary' => 'Voir nos agences',

        'pillars_kicker' => 'Pourquoi ?',
        'pillars_title' => 'Pourquoi choisir Normes Rénovation ?',
        'pillars_subtitle' => 'Notoriété et confiance · Formation et accompagnement · Croissance et opportunités',
        'pillars' => [
            ['icon' => 'shield-check', 'title' => 'Marque reconnue', 'text' => 'Bénéficiez de la notoriété et de la confiance associées à Normes Rénovation.'],
            ['icon' => 'academic-cap', 'title' => 'Soutien continu', 'text' => 'Formation complète, accompagnement personnalisé et outils de gestion adaptés au terrain.'],
            ['icon' => 'arrow-trending-up', 'title' => 'Opportunité de croissance', 'text' => 'Un marché de la rénovation et de la performance énergétique en fort développement.'],
            ['icon' => 'light-bulb', 'title' => 'Innovation et qualité', 'text' => 'Process et offres alignées sur les normes et les attentes des clients.'],
            ['icon' => 'user-group', 'title' => 'Réseau solidaire', 'text' => 'Échanges entre franchisés, bonnes pratiques et entraide au quotidien.'],
        ],

        'implantation_title_line1' => 'Déjà présents en',
        'implantation_title_accent1' => 'Bourgogne',
        'implantation_title_accent2' => 'Bretagne',
        'implantation_text' => 'Normes Rénovation est implanté en Bourgogne-Franche-Comté et en Bretagne, avec des solutions de rénovation et de performance énergétique pour les particuliers et les professionnels. En rejoignant le réseau, vous capitalisez sur une expertise locale et une marque déjà identifiée sur ces territoires.',
        'implantation_cta' => 'Voir nos agences',
        'stats' => [
            ['value' => '+3', 'label' => 'Agences', 'text' => 'Réseau en développement sur la France'],
            ['value' => '99%', 'label' => 'Satisfaction', 'text' => 'Objectif qualité sur le terrain'],
            ['value' => 'Ambition', 'label' => 'CA / agence', 'text' => 'Potentiel lié au territoire et au pilotage commercial'],
        ],

        'network_title' => 'Nos franchisés',
        'network_intro' => 'Rejoignez un réseau dynamique sur un marché à fort potentiel. Bénéficiez de notre expertise, de notre accompagnement et de notre marque pour structurer votre développement.',
        'network_items' => [
            ['title' => 'Réseau national', 'text' => 'Plusieurs agences actives — objectif de déploiement maîtrisé.'],
            ['title' => 'Satisfaction réseau', 'text' => 'Un suivi qualitatif et des process communs pour sécuriser l\'expérience client.'],
            ['title' => 'Croissance', 'text' => 'Vision long terme : développement commercial et renfort des équipes.'],
            ['title' => 'Formation', 'text' => 'Centaines d\'heures de formation et d\'accompagnement personnalisé par an pour les équipes.'],
        ],
        'testimonial_text' => '« Devenir agence Normes a été un tournant : le soutien et les outils du réseau m\'ont permis d\'accélérer le développement tout en gardant le cap sur la qualité. »',
        'testimonial_author' => 'Fiona — Normes Rénovation Bretagne',

        'steps_title' => 'Comment faire ?',
        'steps_subtitle' => 'Les étapes pour nous rejoindre',
        'steps' => [
            ['title' => 'Envoyez votre candidature', 'text' => 'Remplissez le formulaire en ligne : nous étudions votre profil et votre secteur géographique.'],
            ['title' => 'Entretien & analyse', 'text' => 'Échanges avec notre équipe pour valider l\'adéquation du territoire et du projet.'],
            ['title' => 'Proposition & formation', 'text' => 'Remise des engagements, planning de formation et mise à disposition des outils réseau.'],
            ['title' => 'Ouverture & suivi', 'text' => 'Lancement de votre agence avec accompagnement continu et reporting.'],
        ],

        'faq_title' => 'Ce qu\'il faut savoir (F.A.Q.)',
        'faq' => [
            ['q' => 'Quels sont les coûts associés à la franchise Normes Rénovation ?', 'a' => 'Les coûts varient selon la localisation, la taille du territoire et le projet d\'implantation. Nous vous fournissons une estimation personnalisée après analyse de votre dossier et entretien avec notre équipe.'],
            ['q' => 'Quel soutien puis-je attendre de Normes en tant que franchisé ?', 'a' => 'Formation initiale et continue, méthodes commerciales et techniques, outils de pilotage, communication de marque, appui juridique et commercial, et mise en relation avec le réseau d\'agences.'],
            ['q' => 'Quelles sont les qualifications requises pour devenir franchisé Normes ?', 'a' => 'Vous devez avoir un profil entrepreneurial, une capacité d\'investissement adaptée, l\'envie de développer une équipe locale sur le long terme, et partager nos exigences de qualité et de conformité RGE.'],
            ['q' => 'Comment se déroule le processus de franchise avec Normes ?', 'a' => 'Après envoi du formulaire, nous vous recontactons pour un entretien de qualification, l\'analyse du territoire, la validation du business plan, puis la signature des documents et le planning de formation / ouverture.'],
        ],

        'form_kicker' => 'C\'est à vous',
        'form_title' => 'Commencer votre dossier',
        'form_intro' => 'Décrivez votre projet en quelques lignes : un expert Normes Rénovation vous recontacte pour un échange structuré et confidentiel.',
        'form_submit' => 'Envoyer ma candidature',
        'form_rgpd' => 'Les informations transmises sont destinées à l\'étude de votre dossier. Vous pouvez solliciter l\'accès, la rectification ou la suppression de vos données conformément au RGPD.',
    ],
];
